// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/config/create-page": {
            "post": {
                "tags": [
                    "配置"
                ],
                "summary": "创建页面",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.CreatePageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/api/config/menus": {
            "get": {
                "tags": [
                    "配置"
                ],
                "summary": "获取菜单",
                "responses": {}
            }
        },
        "/api/config/page": {
            "get": {
                "tags": [
                    "配置"
                ],
                "summary": "获取页面配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/config/pages": {
            "get": {
                "tags": [
                    "配置"
                ],
                "summary": "获取页面配置",
                "parameters": [
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/adminloginInfo": {
            "get": {
                "tags": [
                    "登录"
                ],
                "summary": "获取管理员登录信息",
                "responses": {}
            }
        },
        "/api/login/logout": {
            "get": {
                "tags": [
                    "登录"
                ],
                "summary": "注销",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/login/phone": {
            "post": {
                "tags": [
                    "登录"
                ],
                "summary": "手机号密码登录",
                "parameters": [
                    {
                        "description": "cansh ",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.LoginDto"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "config.CreatePageDto": {
            "type": "object",
            "required": [
                "config",
                "extend",
                "name",
                "path"
            ],
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "extend": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "login.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API 文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
