definitions:
  login.LoginDto:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  page.CreatePageReq:
    properties:
      config:
        type: string
      extend:
        type: string
      icon:
        type: string
      name:
        type: string
      path:
        type: string
    required:
    - config
    - name
    - path
    type: object
  page.DeletePageReq:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
info:
  contact: {}
  title: API 文档
  version: "1.0"
paths:
  /api/config/page:
    get:
      parameters:
      - description: path
        in: query
        name: path
        required: true
        type: string
      responses: {}
      summary: 页面详情
      tags:
      - 页面
  /api/login/adminloginInfo:
    get:
      responses: {}
      summary: 获取管理员登录信息
      tags:
      - 登录
  /api/login/logout:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 注销
      tags:
      - 登录
  /api/login/phone:
    post:
      parameters:
      - description: 'cansh '
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/login.LoginDto'
      responses: {}
      summary: 手机号密码登录
      tags:
      - 登录
  /api/menu/list:
    get:
      responses: {}
      summary: 菜单列表
      tags:
      - 菜单
  /api/page/create:
    post:
      parameters:
      - description: 参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/page.CreatePageReq'
      responses:
        "200":
          description: OK
          schema:
            type: number
      summary: 创建页面
      tags:
      - 页面
  /api/page/delete:
    post:
      parameters:
      - description: 参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/page.DeletePageReq'
      responses:
        "200":
          description: OK
          schema:
            type: number
      summary: 删除页面
      tags:
      - 页面
  /api/page/list:
    get:
      parameters:
      - in: query
        name: name
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: path
        type: string
      - in: query
        name: perPage
        type: integer
      responses: {}
      summary: 页面列表
      tags:
      - 页面
  /api/page/update:
    post:
      parameters:
      - description: 参数
        in: body
        name: params
        required: true
        schema:
          additionalProperties: true
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: number
      summary: 更新页面
      tags:
      - 页面
swagger: "2.0"
