definitions:
  config.CreatePageDto:
    properties:
      config:
        type: string
      extend:
        type: string
      name:
        type: string
      path:
        type: string
    required:
    - config
    - name
    - path
    type: object
  config.DeletePageDto:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  config.UpdatePageDto:
    properties:
      config:
        type: string
      extend:
        type: string
      id:
        type: integer
      name:
        type: string
      path:
        type: string
    required:
    - config
    - id
    - name
    - path
    type: object
  login.LoginDto:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
info:
  contact: {}
  title: API 文档
  version: "1.0"
paths:
  /api/config/create-page:
    post:
      parameters:
      - description: 参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/config.CreatePageDto'
      responses:
        "200":
          description: OK
          schema:
            type: number
      summary: 创建页面
      tags:
      - 配置
  /api/config/delete-page:
    post:
      parameters:
      - description: 参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/config.DeletePageDto'
      responses:
        "200":
          description: OK
          schema:
            type: number
      summary: 删除页面
      tags:
      - 配置
  /api/config/menus:
    get:
      responses: {}
      summary: 获取菜单
      tags:
      - 配置
  /api/config/page:
    get:
      parameters:
      - description: path
        in: query
        name: path
        required: true
        type: string
      responses: {}
      summary: 获取页面配置
      tags:
      - 配置
  /api/config/pages:
    get:
      parameters:
      - in: query
        name: name
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: path
        type: string
      - in: query
        name: perPage
        type: integer
      responses: {}
      summary: 获取页面配置
      tags:
      - 配置
  /api/config/update-page:
    post:
      parameters:
      - description: 参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/config.UpdatePageDto'
      responses:
        "200":
          description: OK
          schema:
            type: number
      summary: 更新页面
      tags:
      - 配置
  /api/login/adminloginInfo:
    get:
      responses: {}
      summary: 获取管理员登录信息
      tags:
      - 登录
  /api/login/logout:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 注销
      tags:
      - 登录
  /api/login/phone:
    post:
      parameters:
      - description: 'cansh '
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/login.LoginDto'
      responses: {}
      summary: 手机号密码登录
      tags:
      - 登录
swagger: "2.0"
